# -*- coding: utf-8 -*-
"""Segment_anything_model(SAM).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1znLA1X86WWLw_UxRw340YA2FGPsY9BiN
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install leafmap
# %pip install localtileserver
# %pip install segment-geospatial
# %pip install fiona

import leafmap

m = leafmap.Map()
m

"""Support for third party widgets will remain active for the duration of the session. To disable support:"""

import samgeo

from samgeo.common import tms_to_geotiff
from samgeo import SamGeo

m = leafmap.Map(center =[16.2855, 73.6845], zoom=18, height='800px')
m.add_basemap("Satellite")
m

# bbox = [-51.2565, -22.1777, -51.2512, -22.175]
bbox = [73.6750, 16.2750, 73.6950, 16.3000]

image = "image.tif"
tms_to_geotiff(output=image, bbox=bbox, zoom=19, source="Satellite", overwrite=True)

sam = SamGeo(
    model_type="vit_h",
    automatic=False,
    sam_kwargs=None,
)

sam.set_image(image)

# boxes = [
#         [-51.2546, -22.1771, -51.2541, -22.1767],
#         [-51.2538, -22.1764, -51.2535, -22.1761],
#     ]

# The previous boxes variable was a list of points, not bounding boxes.
# The sam.predict function expects bounding boxes in the format [minx, miny, maxx, maxy].
# I've modified the boxes variable to contain two bounding boxes for the area of interest.
boxes = [
    [73.67898847420211, 16.291537674680022, 73.67963220436569, 16.292443899952218],
    [73.6795, 16.291, 73.680, 16.2915], # Added another example bounding box
]

sam.predict(boxes=boxes,point_crs="EPSG:4326",output="mask.tif",dtype="uint8")

m.add_raster("mask.tif", opacity=0.5, camp="viridis", nodata=0, layer_name="mask")

url ="https://raw.githubusercontent.com/dnyanda12/Ass_BigData/refs/heads/main/Tarandale_village_kankavli.geojson"
geojson = "Tarandale_village_kankavli.geojson"
leafmap.download_file(url,geojson,overwrite=True)

sam.predict(boxes=boxes, point_crs="EPSG:4326", output="github.tif",dtype="uint8",)

m.add_raster("github.tif", camp="viridis", nodata=0, layer_name="mask")

m